services:
    mysql:
        image: mysql:8
        command: mysqld --disable-log-bin --performance-schema=OFF
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - mysql_data:/var/lib/mysql
        restart: unless-stopped

    nginx:
        image: nginx:1-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src/public:/app/public:ro
        ports:
            - ${NGINX_HOST_PORT}:80
        restart: unless-stopped

    php:
        build: ./php
        volumes:
            - ./src:/app:ro
            - ./src/storage:/app/storage:rw
        restart: unless-stopped

volumes:
    mysql_data:
